---
title: "Discrete Probability"
output:
  html_document:
    df_print: paged
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Produce a PDF with solutions to the following problems, and submit the PDF on Canvas; due 1/16, 11:59pm. (There is nothing to write up for problem 1.)

1. [Install R and RStudio](installRStudio.html) on your laptop. R and RStudio are free and very powerful. Alternatively, you can use the computers in the library, or you can use the [cloud version](https://posit.cloud/), which is free but with some limitations. 

2. Consider a *one-dimensional random walk*: The walker starts at the point 0 on the number line. To determine the next step, the walker flips a coin. If heads, the walker walks one unit to the right (in the positive direction). If tails, the walker walks one unit to the left. Let $N$ be the number of steps, and let $D$ be the distance from zero on the number line after $N$ steps. Notice that $D$ is a random variable taking positive integer values in the interval $[0,N]$. Use a simulation in R to produce a graph of the distribution of $D$ when $N = 100$, and to compute the average distance from zero that your simulated walkers reach after 100 steps. Use at least 10,000 replications. Include your code and the graph in your write-up. (Hint: in R, you can use the `abs()` function to get the absolute value.)

3. Do Exercises 4, 5, 6, and 14 in [GS], pp. 35-36.
