---
title: "PCR, Lasso, and Ridge Bake-Off"
output:
  html_document:
    df_print: paged
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please submit your written work as a PDF produced by your method of choice, or as a Word Document or Google Doc. **This written document should contain all the relevant output and graphics, as well as written answers to all the questions.** Please also upload a separate R script (`filename.R`) with the code that you used to answer the questions (code only, no output): due 4/11, 11:59pm. 

1. Do Problem 9 on pages 286-287 of [JWHT], parts (a) through (e), using `tidymodels`. You are predicting the variable `Apps` from the other numeric variables (so eliminate `Private` from the data set.) Use the same training and test set for all parts, so you get a fair comparison between the four methods: linear regression, PCR, lasso, and ridge. (The comparison may be quite sensitive to the initial train/test split, however.)



