---
title: "Random Forests"
output:
  html_document:
    df_print: paged
    theme: spacelab
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please submit your written work as a PDF produced by your method of choice, or as a Word Document or Google Doc. **This written document should contain all the relevant output and graphics, as well as written answers to all the questions.** Please also upload a separate R script (`filename.R`) with the code that you used to answer the questions (code only, no output): due 4/18, 11:59pm. 

1. Consider the `Hitters` data frame in the `ISLR2` package. Make a histogram of the `Salary` variable. How would you describe its distribution?

2. Make two new data frames: `hit_complete` containing all the rows of `Hitters` for which there are no `NA`s, and `hitlog_complete` containing all the rows of `hit_complete`, except with a new variable `logSal` containing the log of the salaries. (Remove the `Salary` variable from `hitlog_complete`.)

3. Make a histogram of the `logSal` variable and compare the distribution to the one you found in part 1.

4. Fit a random forest model on `hit_complete` to predict `Salary` from the other variables. Record the OOB MSE, RMSE, and pseudo-$R^2$.

5. Fit a random forest model on `hitlog_complete` to predict `logSal` from the other variables. Record the OOB MSE, RMSE, and pseudo-$R^2$.

6. Compare the results of 4 and 5. Which model is better? To compare the RMSEs, take into account the transformation on $Y$ that was performed. 

7. Create a 75/25 train-test split of both data frames. (Use the same split on each.) Compare testing set RMSE of the predicted salary (for the log-transformed model, you will have to untransform it.) Also compute a testing set RMSE for a linear regression model on each.

8. Find the five most important variables for the random forest models on `hit_complete` and `hitlog_complete`.

9. Fit a linear regression model to both `hit_complete` and `hitlog_complete`. List the five most significant predictors, and compare to (8).



